forum/urls.py
from django.urls import path, re_path

from .views import addInForum, addInDiscussion, home

app_name = 'forum'

urlpatterns = [
    path('home/', home, name='home'),
    path('addInForum/', addInForum, name='addInForum'),
    path('addInDiscussion/', addInDiscussion, name='addInDiscussion'),

]

host/urls.py
from django.urls import path
from . import views

app_name = 'host'

urlpatterns = [
    path('all_hosts/', views.all_hosts, name='all_hosts'),
    path('create_host/', views.create_host, name='create_host'),
    path('delete_host/<host_id>', views.delete_host, name='delete_host'),
    path('edit_host/<int:host_id>/', views.edit_host, name='edit_host'),
    path('export_pdf', views.export_pdf, name="export_pdf"),
    path('export_excel', views.export_excel, name="export_excel"),
]

safehaven/urls.py
from django.contrib import admin
from django.urls import path, include
from. import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from safehaven import views
from django.shortcuts import redirect




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage, name='homepage'),
    path('hosted/',include('hosted.urls')),
    path('aid_org_list/', include('aid_org.urls')),
    path('about/',views.about, name='about'),
    path('success_story/', include('success_story.urls')),
    path('Donations/',include('Donations.urls'), name='Donations)'),
    path('Report/',include('Report.urls')),
    path('admin_page/', views.admin, name='admin_page'),
    path('reports',views.reports,name='reports'),
    path('forum/', include('forum.urls'), name='forum'),
    path('host/', include('host.urls'), name='host'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models



# parent model
class forum(models.Model):
    name = models.CharField(max_length=200, default="אנונימי", verbose_name="שם")
    email = models.EmailField(max_length=200, null=True, verbose_name="אימייל")  # only email allowed
    topic = models.CharField(max_length=300, verbose_name="נושא")
    description = models.TextField(default=None, blank=True, verbose_name="תיאור")
    date_created = models.DateTimeField(auto_now_add=True, null=True, verbose_name="תאריך")

    def __str__(self):
        return str(self.topic)
    class Meta:
        verbose_name_plural = "בקשות תרומה"


# child model
class Discussion(models.Model):
    forum = models.ForeignKey(forum, blank=True, on_delete=models.CASCADE, default=None, verbose_name="הנושא עליו תרצה להגיב")
    discuss = models.TextField(max_length=5000, default=None, blank=True, verbose_name="התגובה")
    name = models.CharField(max_length=100, blank=True, default=None, verbose_name="שם")

    def __str__(self):
        return str(self.forum)
    class Meta:
        verbose_name_plural = "תגובות לבקשות תרומה"

forum/forms.py
from django.forms import ModelForm
from .models import *


class CreateInForum(ModelForm):  # subject
    class Meta:
        model = forum
        fields = "__all__"


class CreateInDiscussion(ModelForm):  # comment
    class Meta:
        model = Discussion
        fields = ['name', 'forum', 'discuss']

forum/views.py
from django.shortcuts import render, redirect
from .models import forum, Discussion
from .forms import *


def home(request):
    '''the function collect all the database data for forum and display it on a page '''
    forums = forum.objects.all()  # getting all subject -> to send for the template and display them
    count = forums.count()  # counting all subjects to show the count in the template
    discussions = []  # List of comments
    comment = CreateInDiscussion()
    for i in forums:
        discussions.append(i.discussion_set.all())  # adding the comments to each forum

    context = {'forums': forums,  # a dictionary to send all the info to the template
               'count': count,
               'discussions': discussions,
               'comment': comment}
    return render(request, 'forum/home.html', context)


def addInForum(request):
    ''' function to add new subject to talk about in the forum '''
    if request.method == 'POST':
        form = CreateInForum(request.POST)  # the subject form with POST data
        if form.is_valid():  # validation check
            form.save()     # if valid we need to save
            return redirect('forum:home')  # if fill correctly the comment will add we be back in the forum home page

    # request.method == 'GET'
    form = CreateInForum()  # empty subject form
    context = {'form': form}  # a dictionary to send all the info to the template
    return render(request, 'forum/addInForum.html', context)


def addInDiscussion(request):
    ''' function to add new comment to a specific subject '''
    msg = None
    if request.method == 'POST':
        form = CreateInDiscussion(request.POST)  # the comment form with POST data

        if form.is_valid() and form.cleaned_data.get('forum') != None:  # validation check
            form.save()  # if valid we need to save
            return redirect('forum:home')  # if fill correctly the comment will add we be back in the forum home page

        if form.cleaned_data.get('forum') == None:  # o send a proper error msg
            msg = 'יש לבחור נושא תקין עליו תרצה להגיב'

    # request.method == 'GET' or not Valid form
    form = CreateInDiscussion()  # empty comment form
    context = {'form': form, 'msg': msg}  # a dictionary to send all the info to the template
    return render(request, 'forum/addInDiscussion.html', context)  # GET or not valid form render the empty form

forum/templates/forum/addInDiscussion.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}

<head>
    <style>
          .add-forum{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>

</head>
    {% if msg %}
        <b>{{ msg }}</b>
    {% endif %}
<form class="add-forum" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="הגב">
</form>
{% endblock %}

forum/templates/forum/addInForum.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}

        <style>
            .add-forum {
                border: 4px solid black;
                margin: 0 auto;
                padding: 40px;
                width: fit-content;
            }
        </style>





    <div>
    <form class="add-forum" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-success" value="שלח">
    </form>
        </div>
{% endblock %}

forum/templates/forum/home.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}



    <style>
        .box {
            border: 2px solid black;
            margin: 0 auto;
        }
    </style>

<center>



<br>
    <br>
    <h1><b>בקשות: {{ count }} </b></h1> <br>

    {% if user.is_authenticated and not user.is_superuser %}
            <a role="button" href="{% url 'forum:addInDiscussion' %} " class="btn btn-dark">רוצה להגיב?</a>
        {% elif user.is_superuser %}
            <a role="button" href="{% url 'forum:addInForum' %} " class="btn btn-dark">בקשת תרומה חדשה</a>
            <a role="button" href="{% url 'forum:addInDiscussion' %} " class="btn btn-dark">רוצה להגיב?</a>
        {% else %}
            <a role="button" href="{% url 'forum:addInForum' %} " class="btn btn-dark">בקשת תרומה חדשה</a>

    {% endif %}
</center>
    <div class="card-columns" style="padding: 10px; margin: 20px;"></div>
    <br>

    {% for forum in forums %}
        <div class="card box container">
            <h3>{{ forum.topic }}</h3>
            <p>{{ forum.description }}</p>


            <p style="text-align:right"> מאת: {{ forum.name }} <br>
                מייל - {{ forum.email }}</p>

            <hr>

            {% for discuss in discussions %}
                {% for objs in discuss %}
                    {% if objs.forum == forum %}
                        <b> מאת: {{ objs.name }}  </b>
                        <br>
                        {{ objs.discuss }}
                        <hr>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <form method="POST">
                {% csrf_token %}
            </form>
        </div>
        <br>

    {% endfor %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>


{% endblock %}