host/urls.py
from django.urls import path
from . import views

app_name = 'host'

urlpatterns = [
    path('all_hosts/', views.all_hosts, name='all_hosts'),
    path('create_host/', views.create_host, name='create_host'),
    path('delete_host/<host_id>', views.delete_host, name='delete_host'),
    path('edit_host/<int:host_id>/', views.edit_host, name='edit_host'),
    path('export_pdf', views.export_pdf, name="export_pdf"),
    path('export_excel', views.export_excel, name="export_excel"),
]

safehaven/urls.py
from django.contrib import admin
from django.urls import path, include
from. import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from safehaven import views
from django.shortcuts import redirect




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage, name='homepage'),
    path('hosted/',include('hosted.urls')),
    path('aid_org_list/', include('aid_org.urls')),
    path('about/',views.about, name='about'),
    path('success_story/', include('success_story.urls')),
    path('Donations/',include('Donations.urls'), name='Donations)'),
    path('Report/',include('Report.urls')),
    path('admin_page/', views.admin, name='admin_page'),
    path('reports',views.reports,name='reports'),
    path('forum/', include('forum.urls'), name='forum'),
    path('host/', include('host.urls'), name='host'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

host/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# create a new model for report app

class hostReq(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    fullname = models.CharField(max_length=100, verbose_name="שם ושם משפחה ")
    street = models.CharField(max_length=100, default='', verbose_name="רחוב ")
    city = models.CharField(max_length=100, verbose_name="עיר ")
    housetype = models.CharField(max_length=15, verbose_name="סוג הנכס ")
    rooms = models.IntegerField(verbose_name="מספר חדרים ")
    beds = models.IntegerField(verbose_name="מספר מיטות ")
    kosher = models.BooleanField(verbose_name="כשרות ")
    phone = models.CharField(max_length=10, verbose_name="טלפון ")
    email = models.EmailField(max_length=100, verbose_name="אימייל ")
    description = models.TextField(blank=True, verbose_name="תיאור הנכס ")
    thumb = models.ImageField(upload_to='media/', blank=True, verbose_name="תמונה של הנכס ")
    is_occupied = models.BooleanField(default=False, verbose_name="האם הנכס תפוס")
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def get_kosher_status(self):
        return 'כן' if self.kosher else 'לא'


    def __str__(self):
        return self.fullname


    class Meta:
        verbose_name_plural = "בקשות אירוח"

host/forms.py
from django.forms import ModelForm
from .models import hostReq


class HostForm(ModelForm):
    class Meta:
        model = hostReq
        fields = ['fullname', 'street', 'city' , 'housetype',
                  'rooms', 'beds', 'kosher','phone',
                  'email', 'description', 'thumb','is_occupied']

host/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from .models import hostReq
from .forms import HostForm
from django.http import HttpResponse, FileResponse
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
import io
import xlwt
from .filters import host_filter
from django.http import HttpResponseForbidden


from django.contrib.auth.decorators import login_required, permission_required
from .decorators import user_is_host
from django.core.exceptions import PermissionDenied



@login_required
def create_host(request):
    # Print out the names of all the groups the user belongs to
    print([group.name for group in request.user.groups.all()])

    # Check if the user is part of the 'מארח' group or is a superuser
    if not request.user.groups.filter(name='מארח').exists() and not request.user.is_superuser:
        raise PermissionDenied  # or redirect to a different page

    if request.method == 'POST':
        form = HostForm(request.POST)
        if form.is_valid():
            host = form.save(commit=False)
            host.user = request.user
            host.save()
            return redirect('host:all_hosts')
    else:
        form = HostForm()
    return render(request, 'host/create_host.html', {'form': form})


def all_hosts(request):
    hosts = hostReq.objects.order_by('-date')
    my_host_filter = host_filter(request.GET, queryset=hosts)
    hosts = my_host_filter.qs
    return render(request, 'host/all_hosts.html', {'hosts': hosts, 'host_filter': my_host_filter})

def delete_host(request, host_id):
    host = get_object_or_404(hostReq, pk=host_id)
    if request.user != host.user and not request.user.is_superuser:
        return HttpResponseForbidden()
    host.delete()
    return redirect('host:all_hosts')

def edit_host(request, host_id):
    host = get_object_or_404(hostReq, pk=host_id)
    if request.user != host.user and not request.user.is_superuser:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = HostForm(request.POST, request.FILES, instance=host)
        if form.is_valid():
            form.save()
            return redirect('host:all_hosts')
    else:
        form = HostForm(instance=host)
    return render(request, 'host/create_host.html', {'form': form})

def export_excel(request):
    """Function for exporting an excel document from the system"""
    response = HttpResponse(content_type='donations/excel')
    response['Content-Disposition'] = 'attachment; filename=hosts' + str(datetime.now()) + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('hosts')  # give a name to the sheet
    row_num = 2  # initial row for objects
    font_style = xlwt.XFStyle()  # set the font of the text
    font_style.font.bold = True

    ws.write(0, 0, 'Hosts report of the "SafeHaven" association:', font_style)  # the title of the file

    columns = ['Name', 'Is Occupied']  # the columns in the table
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # save all the data we need from database
    rows = hostReq.objects.all().values_list('fullname', 'is_occupied')

    font_style = xlwt.XFStyle()

    hosts = hostReq.objects.all()
    total_hosts = hosts.count()
    free_hosts = hosts.filter(is_occupied=False).count()

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, str(row[col_num]), font_style)  # enter all the data to the table

    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    ws.write(total_hosts + 3, 0, 'Total Hosts:', font_style)
    ws.write(total_hosts + 3, 1, str(total_hosts), font_style)  # print the total amount
    ws.write(total_hosts + 4, 0, 'Free Hosts:', font_style)
    ws.write(total_hosts + 4, 1, str(free_hosts), font_style)  # print the total amount

    wb.save(response)  # save the file

    return response

def export_pdf(request):
    """Function for exporting a pdf document from the system"""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)  # creat a new page
    textob = c.beginText()  # creat a text object
    textob.setTextOrigin(inch, inch)  # set the sizes of the text
    pdfmetrics.registerFont(TTFont('Tahoma', 'Tahoma.ttf'))
    textob.setFont("Tahoma", 14)  # set the font of the text

    hosts = hostReq.objects.all()  # designate the model
    lines = []  # creat a new list for the objects

    total_hosts = hosts.count()
    free_hosts = hosts.filter(is_occupied=False).count()

    def is_hebrew(s):
        return all('\u0590' <= c <= '\u05EA' or c == ' ' for c in s)

    # print all data we need
    for host in hosts:
        name = host.fullname
        if is_hebrew(name):
            name = name[::-1]
        lines.append('Host name: ' + name)
        lines.append('Is Occupied: ' + str(host.is_occupied))
        lines.append('    ')
        lines.append('----------------------------------')
        lines.append('    ')

    lines.append('Total Hosts:' + str(total_hosts))
    lines.append('Free Hosts:' + str(free_hosts))

    textob.textLine("Hosts report of the 'SafeHaven' association:")  # the title of the file
    textob.textLine("    ")
    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()  # save the file
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename='hosts.pdf')

host/templates/host/all_hosts.html
{% extends "base_layout.html" %}

{% load static %}

{% block content %}


<html>
<br>

<head>
    <style>
    h1 {
        text-align: center;
    }

    p {
        text-align: center;
    }

     .host-image {
        max-width: 600px;
        max-height: 300px;
    }
     .description-box {
    border: 1px solid black;
    padding: 10px;
    margin-top: 10px;
}

    div {
        text-align: center;
    }

    .aid_org {
        background-color: white;
    }
</style>
</head>

<body>

<h1 class="font-weight-bold text-center">  רשימת בתי אירוח </h1>
<br>

<h3 class="text-center mb-5"> משתמשים הוסיפו עד כה {{ hosts.count }} בתי אירוח </h3>


<form method="GET">
    <b>חיפוש מתקדם:</b>
    <br>
    {{ host_filter.form }}
    <button class='btn btn-outline-dark' type="submit">חפש</button>
</form>

{% for host in hosts %}
<div class="row justify-content-center my-3 aid_org position-relative">
    <div class="col-md-10 d-flex flex-column flex-md-row">
        <div class="d-flex flex-column align-items-start">
            {% if host.thumb %}
            <img class="host-image mb-3" src="{{ host.thumb.url }}" alt="Image of the property">
            {% endif %}
            <div class="description-box">
                <p>תיאור הנכס:{{ host.description }}</p>
            </div>
        </div>
        <div class="position-absolute" style="top: 0; right: -100px;">
            {% if host.is_occupied %}
            <p><span class="dot" style="color: red;">&#9679;</span> הנכס אוכלס</p>
            {% else %}
            <p><span class="dot" style="color: green;">&#9679;</span> פנוי לאירוח</p>
            {% endif %}
        </div>
        <div>
            <h5 class="text-muted">{{ host.date|date:'d/m/Y'|upper }}</h5>
            <br>
            <p>מקום אירוח #{{ forloop.counter }}</p>
            <p>שם: {{ host.fullname }}</p>
            <p>רחוב: {{host.street}}</p>
            <p>עיר: {{ host.city }}</p>
            <p>סוג בית: {{ host.housetype }}</p>
            <p>מספר חדרים: {{ host.rooms }}</p>
            <p>מספר מיטות: {{ host.beds }}</p>
            <p>כשרות: {{ host.get_kosher_status }}</p>
            <p>נייד: {{ host.phone }}</p>
            <p>דוא"ל: {{ host.email }}</p>
            {%  if request.user == host.user or request.user.is_superuser %}
            <br>
            <br>
            <a href="{% url 'host:edit_host' host.id %}" class="btn btn-primary">ערוך</a>
            <a href="{% url 'host:delete_host' host.id %}" class="btn btn-dark">מחק</a>
            <br>
            <br>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
<br>
<br>
{% if request.user == host.user or request.user.is_superuser %}
<a role="button" href="{% url 'host:create_host' %}" class="btn btn-warning">לשיתוף אירוח חדש</a>
{% endif %}
<br>
<br>
{% endblock %}

host/templates/host/create_host.html
{% extends 'base_layout.html' %}
{% block content %}

<!doctype html>
<html lang="he" dir="rtl">
<br>
<html>
<head>
<style>
h1 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>
</head>
<body class >

{% if request.user.groups.all.0.name == 'hosted' %}
    <h1>אין לך הרשאה לצפות בדף זה</h1>
{% else %}
    <h1>טופס אירוח</h1>
    <br>
    <form method="POST" enctype="multipart/form-data" class = "aid_org">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-dark">שלח</button>
    </form>
    <br>
    <br>
{% endif %}

{% endblock %}