Donations/urls.py
from django.urls import path
from . import views

app_name = 'Donations'

urlpatterns = [
    path('new/', views.donates_form, name="new"),  # שולח לטופס
    path('Thankyou/', views.Thankyou, name="Thankyou"),  # שולח לטופס
    path('export_pdf', views.export_pdf, name="export_pdf"),
    path('export_excel', views.export_excel, name="export_excel"),


]

Report/urls.py
from django.urls import path
from . import views

app_name = 'Report'

urlpatterns = [
    path('all_reports/', views.all_reports, name='all_reports'),
    path('createReport/', views.createReport, name='createReport'),
    path('deleteReport/<report_id>', views.deleteReport, name='deleteReport'),
]

aid_org/urls.py
from django.urls import path
from. import views

app_name = 'aid_org'

urlpatterns = [
    path('', views.aid_org_list, name="list"),
    path('<slug:slug>/', views.aid_org_detail, name = "detail"),
]

forum/urls.py
from django.urls import path, re_path

from .views import addInForum, addInDiscussion, home

app_name = 'forum'

urlpatterns = [
    path('home/', home, name='home'),
    path('addInForum/', addInForum, name='addInForum'),
    path('addInDiscussion/', addInDiscussion, name='addInDiscussion'),

]

host/urls.py
from django.urls import path
from . import views

app_name = 'host'

urlpatterns = [
    path('all_hosts/', views.all_hosts, name='all_hosts'),
    path('create_host/', views.create_host, name='create_host'),
    path('delete_host/<host_id>', views.delete_host, name='delete_host'),
    path('edit_host/<int:host_id>/', views.edit_host, name='edit_host'),
    path('export_pdf', views.export_pdf, name="export_pdf"),
    path('export_excel', views.export_excel, name="export_excel"),
]

hosted/urls.py
from django.urls import path
from. import views

app_name = 'hosted'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

safehaven/urls.py
from django.contrib import admin
from django.urls import path, include
from. import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from safehaven import views
from django.shortcuts import redirect




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage, name='homepage'),
    path('hosted/',include('hosted.urls')),
    path('aid_org_list/', include('aid_org.urls')),
    path('about/',views.about, name='about'),
    path('success_story/', include('success_story.urls')),
    path('Donations/',include('Donations.urls'), name='Donations)'),
    path('Report/',include('Report.urls')),
    path('admin_page/', views.admin, name='admin_page'),
    path('reports',views.reports,name='reports'),
    path('forum/', include('forum.urls'), name='forum'),
    path('host/', include('host.urls'), name='host'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Report/models.py
from django.db import models
from datetime import date


# create a new model for report app

class report(models.Model):
    date = models.DateField(default=date.today, verbose_name="תאריך ")  # date of the report
    name = models.CharField(max_length=100, verbose_name="שם המדווח ")  # name of the reporter
    text = models.TextField(blank=True, verbose_name="תוכן הדיווח ")  # the content of the report

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "דיווחים"

Report/forms.py
from django.forms import ModelForm
from .models import report


class ReportForm(ModelForm):
    class Meta:
        model = report
        fields = ['date', 'name', 'text']

Report/views.py
from django.shortcuts import render, redirect
from .models import report
from .forms import ReportForm


def createReport(request):
    """the function creat a new report according to the request of the user and save it in the database"""
    if request.method == 'POST':
        form = ReportForm(request.POST)  # creat a form for the report
        if form.is_valid():
            new_report = form.save(commit=False)
            new_report.save()  # saving the new report in the database
            return redirect('Report:all_reports')  # refers to the page of all reports
    return render(request, 'Report/createReport.html', {'form': ReportForm()})


def all_reports(request):
    """the function presents all reports in the order of their arrival"""
    reports = report.objects.order_by('-date')
    return render(request, 'Report/all_reports.html', {'reports': reports})


def deleteReport(request, report_id):
    """the function delete a report according to the request of the user (volunteer only) and delete it
     from the database """
    Report = report.objects.get(pk=report_id)
    Report.delete()  # delete the report from the database
    return redirect('Report:all_reports')  # refers to the page of all reports

templates/base_layout.html
{% load static %}
{% load user_filters %}
<!doctype html>
<html lang="he" dir="rtl">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <link rel="icon" type="image/png" href="{% static 'safeHavenLogo.png' %}">

    <title>Safe Haven</title>

</head>

<body>
<nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">

        <a class="navbar-brand" href="{% url 'homepage' %}">
            <div class="logo-frame">
                <img src="{% static 'safeHavenLogo.png' %}" width="100" height="90" class="d-inline-block align-top" alt="Safehaven's Logo">
            </div>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">

                   {% if user.is_authenticated %}
                   <li>
                   <a role="button" href="{% url 'host:all_hosts' %}" class="btn btn-primary">רוצה להתארח? </a>
                    </li>&#160
                    {% endif %}
                {% if user|has_group:'מארח' or user.is_superuser %}
                    <li>
                    <a role="button" href="{% url 'host:create_host' %}" class="btn btn-primary">רוצה לארח? </a>
                    </li>&#160
                {% endif %}
                {% if user.is_authenticated %}
                <li>
                    <a role="button" href="{% url 'aid_org:list' %}" class="btn btn-info">ארגוני סיוע</a>
                </li>
                &#160

                <li>
                    <a role="button" href="{% url 'success_story:all_stories' %}" class="btn btn-info">סיפורי הצלחה</a>
                </li>
                &#160

                <li>
                    <a role="button" href="{% url 'forum:home' %}" class="btn btn-info">בקשת תרומה</a>
                </li>
                &#160
                {% endif %}

                {% if user.is_authenticated and user.is_superuser %}

                 <li>
                    <a role="button" href="{% url 'reports' %}" class="btn btn-info">דו"חות</a>
                </li>
                &#160
                {% endif %}

                <li>
                    <a role="button" href="{% url 'Donations:new' %}" class="btn btn-info">תרום כסף</a>
                </li>
                &#160



                 {% if user.is_authenticated and user.is_superuser %}

                <li>
                    <a role="button" href="{% url 'Report:all_reports' %}" class="btn btn-danger">דיווחים</a>
                </li>
                &#160
                {% endif %}

                {% if user.is_authenticated %}

                <li>
                    <a role="button" href="{% url 'Report:createReport' %}" class="btn btn-danger">לדווח</a>
                <li>&#160


                <li>
                    <form class="logout-link" action="{% url 'hosted:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-dark">התנתקות</button>
                    </form>
                </li>
                &#160
                {% endif %}





                {% if not user.is_authenticated %}

                <li>
                    <a role="button" href="{% url 'hosted:signup' %}" class="btn btn-primary">הרשמה</a>
                </li>
                &#160

                <li>
                    <a role="button" href="{% url 'hosted:login' %}" class="btn btn-dark">התחברות</a>
                </li>
                &#160



                {% endif %}

                {% if user.is_authenticated and user.is_superuser %}
                <li>
                <a role="button" href="{% url 'admin_page' %}" class="btn btn-secondary">ניהול</a>
                </li>&#160


                {% endif %}

            </ul>
        </div>
    </div>
</nav>
{% if user.is_authenticated %}
<div class="center-text">
    <b>מחובר בתור {{user.username}}</b>
</div>
{% endif %}
<div class="container" dir="rtl">

    {% block content %}
    {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/homepage.html
{% extends 'base_layout.html' %}
{% load static %}



{% block content %}
    <head>
        <meta charset="utf-8">
        <title>ברוכים הבאים ל- SafeHaven</title>
        <br>
        <style>
            .banner-image {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 800px;  /* Adjust width as needed */
        height: auto;
            }
            .aid_org {
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
                text-align: center;
            }
            .banner-image, .aid_org p {
                align-self: center;
            }
        </style>
    </head>
    <body>

        <h1></h1>


       <img class="banner-image" src="{% static 'YAHAD.jpeg' %}" >
        <br>
        <br>

        <!-- About Us Section -->
        <div class="about-section ">
            <h2 class = "center-text">אודותינו</h2>
<br>
            <p class="aid_org">ברוכים הבאים ל-SafeHaven, פרויקט חדשני שנועד לספק מקלט זמני ותמיכה למשפחות הנתקלות במשבר. בעולם שבו אסונות וחירום יכולים להתרחש בכל רגע, המשימה שלנו היא לאפשר מקום בטוח ותמיכה למי שזקוק להם ביותר.

הפלטפורמה שלנו מחברת בין משפחות במצוקה לבין אנשים וארגונים עם לב גדול, המציעים מקום לינה, ציוד ותרומות. דרך שיתוף פעולה זה, אנו שואפים ליצור רשת תמיכה קהילתית שמובילה לחיזוק החוסן והביטחון של המשפחות הנפגעות.

SafeHaven פועלת מתוך הבנה שהמשימה שלנו היא לא רק לספק מקלט פיזי, אלא גם לפעול למען שיקום התקווה והכוח למשפחות. אנו מתמקדים בשלוש קבוצות עיקריות: משפחות המחפשות מקום לינה ותמיכה, אנשים ומוסדות המציעים את המקום והמשאבים, ומתנדבים וארגונים התומכים במאמצים אלה.

אנו מאמינים בחשיבות השיתוף ובחוזק הקהילה. דרך SafeHaven, כל אחד יכול לתרום, להיות חלק מהשינוי, ולהציע יד חמה למי שצריך. הצטרפו אלינו והיו חלק מהמשימה ליצור עולם טוב יותר ובטוח יותר לכולם. </p>
        </div>
    </body>
{%  endblock  %}

templates/reports.html
{% extends "base_layout.html" %}

{% load static %}

{% block content %}



    <br>
    <br>

    <div class="row"/>
    <head>
        <style>
            h1 {
                text-align: center;
            }

            p {
                text-align: center;
            }

            div {
                text-align: center;
            }

        </style>
    </head>
    <body>

    <br>
    <br>
    <br>
<div>
<br >
    <h1 class="font-weight-bold text-center"> הפקת דו"חות </h1>
<br>
{% if user.is_superuser %}
</div>
    <div class="row  ">
        <div class="col-md " >
                <table class="table table-sm" ]>
                    <tr >

                    </tr>


<tr>
    <th class = "line">


<h4><b>דו"ח מצב תרומות:  </b></h4>
<a href="{% url 'Donations:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a href="{% url 'Donations:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

        <h4><b>דו"ח מצב אירוחים פעילים:  </b></h4>
<a href="{% url 'host:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a href="{% url 'host:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160


</th>


            </table>
        </div>

</div>


    {% endif %}
{% endblock %}